services:
  - type: static
    name: budget-tracker-client
    env: static
    buildCommand: npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
